### ISSUE TITLE
Vector icons

### ISSUE THREAD

**Issue by hickford** [rauchg/chrome-spdy-indicator#18]
Would it be possible to replace the raster icons with scalable vector svgs? Right now the pngs look crummy on computers with large font size ('dpi').

![crummy](https://cloud.githubusercontent.com/assets/105314/4590555/338fe66e-5061-11e4-9dcd-5ebad20757b2.png)

The star and stack icons look good, but the spdy (and envelope) icons are pixelated.

**Comment by specious** [comment]
It seems page actions are allowed to use 19x19 icons as well as 38x38 icons for high dpi displays: https://developer.chrome.com/extensions/pageAction#manifest

The icons are currently 10x17 pixels, so I suppose that would mean re-rendering them at 20x34.

@rauchg, do you have the original graphics?

**Comment by rauchg** [comment]
I believe I don't, but we can probably use a similar icon from The Noun Project?

**Comment by kav2k** [comment]
It's not possible to use a vector icon for this, but the proper approach is to recreate all icons as 19x19 and 38x38 (to avoid stretching, see https://bugs.chromium.org/p/chromium/issues/detail?id=161618 + https://groups.google.com/a/chromium.org/d/topic/chromium-extensions/7As9MKhav5E/discussion)

**Comment by kav2k** [comment]
The _absolute proper_ way to do this would be to have a monochrome template and render the icon dynamically (color + "badge") via canvas. But 38x38 scale icons are a good first step.
