### ISSUE TITLE
Gradient icon is shown instead of indicator

### ISSUE THREAD

**Issue by Goz3rr** [rauchg/chrome-spdy-indicator#27]
On Chrome 50.0.2633.3 dev-m (64-bit) the icon never changes (stays as icon.png) however the tooltip does change

**Comment by MrArtichaut** [comment]
Same here with Chrome 49.0.2623.39 beta (64-bit)

**Comment by MrArtichaut** [comment]
Works again with Chrome 49.0.2623.47 beta (64-bit)

**Comment by Goz3rr** [comment]
50.0.2645.4 dev-m (64-bit) now, icon shows up again but is very stretched out:

![](http://i.imgur.com/np7JTzx.png)

![](http://i.imgur.com/NgYOrW2.png)
